// Code generated by MockGen. DO NOT EDIT.
// Source: scraper.go

// Package main is a generated GoMock package.
package main

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIScraper is a mock of IScraper interface.
type MockIScraper struct {
	ctrl     *gomock.Controller
	recorder *MockIScraperMockRecorder
}

// MockIScraperMockRecorder is the mock recorder for MockIScraper.
type MockIScraperMockRecorder struct {
	mock *MockIScraper
}

// NewMockIScraper creates a new mock instance.
func NewMockIScraper(ctrl *gomock.Controller) *MockIScraper {
	mock := &MockIScraper{ctrl: ctrl}
	mock.recorder = &MockIScraperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIScraper) EXPECT() *MockIScraperMockRecorder {
	return m.recorder
}

// getResultsFromUrl mocks base method.
func (m *MockIScraper) getResultsFromUrl() ([]FightRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getResultsFromUrl")
	ret0, _ := ret[0].([]FightRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getResultsFromUrl indicates an expected call of getResultsFromUrl.
func (mr *MockIScraperMockRecorder) getResultsFromUrl() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getResultsFromUrl", reflect.TypeOf((*MockIScraper)(nil).getResultsFromUrl))
}
